export const CURRENCY_CODE = {
    INDIAN_RUPEE: 'INR',
    US_DOLLAR: 'USD',
    EURO: 'EUR',
    POUND_STERLING: 'GBP',
    AUSTRALIAN_DOLLAR: 'AUD',
    CANADIAN_DOLLAR: 'CAD',
    SWISS_FRANC: 'CHF',
    JAPANESE_YEN: 'JPY',
    CHINESE_YUAN: 'CNY',
    RUSSIAN_RUBLE: 'RUB',
}