const API_URLS = {
  AUTHENTICATION: {
    LOGIN: '/user/login',
    LOGOUT: '/user/logout',
    REFRESH: '/user/refresh',
    // VERIFY_CODE: '/user/verify-code',
    // RESEND_VERIFICATION_CODE: '/user/resend-verification-code',
    // CHANGE_TEMP_PASSWORD: '/user/change-temp-password',
    // CHANGE_PASSWORD: '/user/change-password',
    // REQUEST_PASSWORD_RESET: '/user/request-password-reset',
    // RESET_PASSWORD: '/user/reset-password',
  },
  USER: {
    CREATE: '/user/create',
    DETAILS: '/user/:id',
    UPDATE: '/user/update/:id',
    DELETE: '/user/delete/:id',
    ENABLE: '/user/enable',
    DISABLE: '/user/disable',
    MENU_CONFIG: '/user/init',
    PROFILE_ME: '/user/profile/me',
    LIST: '/user/list',
    CHILD_ROLES: '/user/child-roles',
    CHANGE_TEMP_PASSWORD: '/user/change-temp-password',
    FAMILY_MEMBERS: '/user/family/:familyId/members',
    CHANGE_PASSWORD: '/user/change-password',
  },
  ROLES: {
    CREATE: '/admin/roles/create',
    DETAILS: '/admin/roles/:id',
    UPDATE: '/admin/roles/update/:id',
    DELETE: '/admin/roles/delete/:id',
    LIST: '/admin/roles/list',
    PERMISSIONS: '/admin/permissions',
    CHILD_ROLES: '/admin/roles/child-roles',
    ALL_ROLES: '/admin/roles/all',
  },
  SHARED: {
    DROPDOWN: '/dropdown',
    STATIC_DROPDOWN: '/options',
  },
  CLIENT_CONFIG: '/client-config',
  TRANSLATION: '/translation',
  DASHBOARD: {
    STATS: '/dashboard/stats',
    GROWTH_TRENDS: '/dashboard/growth-trends',
    RECENT_ACTIVITIES: '/dashboard/recent-activities',
    CHURCH_STATS: '/dashboard/church-stats',
    FAMILY_STATS: '/dashboard/family-stats',
    FAMILY_DISTRIBUTION: '/dashboard/family-distribution',
    AGE_DISTRIBUTION: '/dashboard/age-distribution',
    APP_GROWTH_METRICS: '/dashboard/app-growth-metrics',
    INCOME_EXPENSE_TRENDS: '/dashboard/income-expense-trends',
  },
  DIOCESE: {
    CREATE: '/diocese/create',
    DETAILS: '/diocese/:id',
    UPDATE: '/diocese/update/:id',
    DELETE: '/diocese/delete/:id',
    LIST: '/diocese/list',
    ENABLE: '/diocese/enable/:id',
    DISABLE: '/diocese/disable/:id',
  },
  CHURCH: {
    CREATE: '/church/create',
    DETAILS: '/church/:id',
    UPDATE: '/church/update/:id',
    DELETE: '/church/delete/:id',
    LIST: '/church/list',
    ENABLE: '/church/enable/:id',
    DISABLE: '/church/disable/:id',
    
  },
  FAMILY: {
    CREATE: '/family/create',
    DETAILS: '/family/:id',
    UPDATE: '/family/update/:id',
    DELETE: '/family/delete/:id',
    LIST: '/family/list',
    ENABLE: '/family/enable/:id',
    DISABLE: '/family/disable/:id',
    MEMBERS: '/family/:familyId/members',
  },
  ORGANIZATION: {
    CREATE: '/organization/create',
    DETAILS: '/organization/:id',
    UPDATE: '/organization/update/:id',
    DELETE: '/organization/delete/:id',
    LIST: '/organization/list',
    ENABLE: '/organization/enable',
    DISABLE: '/organization/disable',
    DASHBOARD: '/organization/:id/dashboard',
    ADD_MEMBER: '/organization/:id/members',
    REMOVE_MEMBER: '/organization/:id/members/:userId',
    ASSIGN_LEADERSHIP: '/organization/:id/leadership',
    UPDATE_LEADERSHIP: '/organization/leadership/:leadershipId',
    REMOVE_LEADERSHIP: '/organization/leadership/:leadershipId',
  },
  DROPDOWN_CONTEXT: {
    DIOCESES: '/dropdown/context/dioceses',
    CHURCHES: '/dropdown/context/churches',
    FAMILIES: '/dropdown/context/families',
    FAMILY_MEMBERS: '/dropdown/context/:familyId/members',
  },
  PAYMENTS: {
    LIST: '/payments/list',
    INCOME: {
      LIST: '/payments/income/list',
      OVERVIEW: '/payments/income/overview',
      EXPORT: '/payments/income/export',
    },
    EXPENSE: {
      LIST: '/payments/expense/list',
      OVERVIEW: '/payments/expense/overview',
      EXPORT: '/payments/expense/export',
      CREATE: '/payments/expense/create',
    },
    CREATE: '/payments/create',
    UPDATE: '/payments/update/:id',
    DELETE: '/payments/delete/:id',
    CATEGORIES: '/payments/categories',
    SOURCES: '/payments/sources',
    CURRENCIES: '/payments/currencies',
    EXPORT: '/payments/export',
  },
};

export default API_URLS;
